name: Tag creation

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Get the version
        id: version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        shell: bash

      - uses: apexskier/github-semver-parse@v1
        id: semver
        with:
          version: ${{ steps.version.outputs.VERSION }}

      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: Build macOS amd64
        env:
          VERSION: ${{ steps.version.outputs.VERSION }}
          GOOS: darwin
          GOARCH: amd64
        run: go build -o ./rrf.$GOOS-GOARCH -ldflags "-X main.GitCommit=$GITHUB_REF -X main.Version=$VERSION" ./...

      - name: Build linux 386
        env:
          VERSION: ${{ steps.version.outputs.VERSION }}
          GOOS: linux
          GOARCH: 386
        run: go build -o ./rrf.$GOOS-GOARCH -ldflags "-X main.GitCommit=$GITHUB_REF -X main.Version=$VERSION" ./...

      - name: Release
        id: release
        if: ${{ steps.semver.outputs.version }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GH_TOKEN }}
        with:
          draft: true
          tag_name: ${{ steps.version.outputs.VERSION }}
          release_name: ${{ steps.version.outputs.VERSION }}
          prerelease: ${{ !!steps.semver.outputs.prerelease }}

      - name: Attach binaries to release
        uses: skx/github-action-publish-binaries@release-0.14
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: rrf.*

